### ISSUE TITLE
KeyError: 'url' with Debian Buster and python 3.7

### ISSUE THREAD

**Issue by redgloboli** [Snawoot/postfix-mta-sts-resolver#85]
**Describe the bug**
I installed mta-sts-daemon with sudo python3 -m pip install postfix-mta-sts-resolver[redis] and installed the systemd files.

If i run mta-sts-daemon on command line i get:

2022-05-30 20:28:25 INFO     MAIN: MTA-STS daemon starting...
2022-05-30 20:28:25 INFO     MAIN: Starting eventloop...
2022-05-30 20:28:25 INFO     MAIN: uvloop enabled.
2022-05-30 20:28:25 INFO     MAIN: Eventloop started.
Traceback (most recent call last):
  File "/usr/local/bin/mta-sts-daemon", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/postfix_mta_sts_resolver/daemon.py", line 123, in main
    evloop.run_until_complete(amain(cfg, evloop))
  File "uvloop/loop.pyx", line 1448, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/postfix_mta_sts_resolver/daemon.py", line 65, in amain
    await cache.setup()
  File "/usr/local/lib/python3.7/dist-packages/postfix_mta_sts_resolver/redis_cache.py", line 38, in setup
    url = self._opts['url']
KeyError: 'url'

**Expected behavior**
I expected no crash ;)

**Environment (please complete the following information):**
 - OS: Linux
 - Distro: Debian
 - Distro version: Buster (10)
 - Python version: 3.7

**Comment by redgloboli** [comment]
as always, i ask for help and solve it myself... 

i had errors in the config file....
